# .coderabbit.yaml
reviews:
  profile: "chill" # Keeps it from nagging about minor style preferences
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    ignore:
      - "package-lock.json"
      - "yarn.lock"
      - "node_modules/**"
      - "dist/**"
      - "build/**"
      - "**/*.min.js"
      - "**/*.map"
      #- "public/**" # Optional: Ignore static assets if you don't need SVG reviews

chat:
  auto_reply: true
